### ISSUE TITLE
Selfservice view does not seem to get filtered

### ISSUE THREAD

**Issue by jalbstmeijer** [cloos/RT-Extension-BriefHistory#2]
Hi,

I'm testing RT-Extension-BriefHistory-2.00 with RT-4.4.1.

I see the filter working for privileged users, but the self service page for un-privileged users still shows all transactions.

I'm I missing something?

Gr, Justin

**Comment by jalbstmeijer** [comment]
RT-Extension-HistoryFilter-2.01 seems to work in SelfService. That is expected?

**Comment by netsandbox** [comment]
I never included the commit from https://github.com/cloos/RT-Extension-HistoryFilter/commit/452342e in this extension.
I focused more on my RT-Extension-HistoryFilter because it is more flexible than this one.
I can updated this extension, but I need some time, because I currently don't have a working development system available.

**Comment by jalbstmeijer** [comment]
Hi, thanks for your feedback.

For me RT-Extension-HistoryFilter works now, so no hurry.
Not sure why you keep two extensions alive that do the same thing.

Bit off topic: Is it correct both RT-Extension-HistoryFilter and RT-Extension-BriefHistory filter out comments from the SelfService section?
In my case it's exactly what I want, but it is somewhat in contradiction with the config options and undocumented.

Gr, Justin

**Comment by netsandbox** [comment]
> Bit off topic: Is it correct both RT-Extension-HistoryFilter and RT-Extension-BriefHistory filter out comments from the SelfService section?
In my case it's exactly what I want, but it is somewhat in contradiction with the config options and undocumented.

If you just want to filter out comments, you can do this with the `ShowTicketComments` right. Just don't give the people, who shouldn't see comments the `ShowTicketComments` right.

**Comment by netsandbox** [comment]
SelfService filtering is fix in 2.01
